### ISSUE TITLE
Running locally - This site can’t be reached - macOS

### ISSUE THREAD

**Issue by psyklopp** [webamon-org/Democracy#25]
OS: **macOS Monterey 12.5.1**

Followed the steps:

1. Cloned the repo (v0.2.3)
2. Added the API key to `yml` file
3. Ran `docker-compose up`

```yml
version: '3.8'

services:
  console:
    build: ./Console
    ports:
      - "3030:3030"


  sandbox:
    build: ./Sandbox
    ports:
      - "5000:5000"
    environment:
      - queue_worker=true
      - community=true
      - webamon_apikey=my_API_key
```

I navigate to `localhost:3030` in browser (Chrome and Safari).
And it says site cannot be reached.

In the terminal, the last note is `console-1  | webpack compiled with 27 warnings`, which is expected (as seen in the video `3x Commands, 3x Minutes`)
